acode.setPluginInit(async () => {

  const fs = acode.require("fsOperation");

  async function createHTMLProject(basePath, name) {

    const root = `${basePath}/${name}`;

    await fs.createDirectory(root);
    await fs.createDirectory(`${root}/css`);
    await fs.createDirectory(`${root}/js`);
    await fs.createDirectory(`${root}/assets`);

    await fs.writeFile(
      `${root}/index.html`,
`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${name}</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <h1>${name}</h1>
  <script src="js/script.js"></script>
</body>
</html>`
    );

    await fs.writeFile(`${root}/css/style.css`,
`body {
  font-family: Arial;
  margin: 40px;
}`
    );

    await fs.writeFile(`${root}/js/script.js`,
`console.log("${name} ready!");`
    );

    await fs.writeFile(`${root}/README.md`,
`# ${name}

Generated by QuickStart Pro`
    );

    await fs.writeFile(`${root}/.gitignore`,
`node_modules
.env`
    );

    acode.alert("Project Created Successfully 🚀");
  }

  acode.addMenuItem({
    id: "quickstart-pro",
    title: "Create HTML Project",
    onclick: async () => {
      const name = await acode.prompt("Enter Project Name");
      if (!name) return;

      const basePath = await fs.getDirectory();
      await createHTMLProject(basePath, name);
    }
  });

});
